# Generated by Django 4.2.5 on 2023-09-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_ideaitem_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='completed',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='idea',
            name='priority',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
