# Generated by Django 4.2.5 on 2023-09-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_completed_idea_status_alter_idea_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dateAdded',
            field=models.DateField(blank=True),
        ),
    ]
