# Generated by Django 4.2.5 on 2023-09-24 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_idea_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2023, 9, 24, 23, 0, 46, 747868, tzinfo=datetime.timezone.utc)),
        ),
    ]
