# Generated by Django 4.2.5 on 2023-09-22 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_idea_ideaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideaitem',
            name='dateAdded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ideaitem',
            name='idea',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ideaitem',
            name='priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
