# Generated by Django 4.2.5 on 2023-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ideaitem_completed_ideaitem_dateadded_ideaitem_idea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideaitem',
            name='idea',
        ),
        migrations.AddField(
            model_name='ideaitem',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ideaitem',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ideaitem',
            name='priority',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
