# Generated by Django 4.2.5 on 2023-09-24 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_idea_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2023, 9, 24, 22, 40, 46, 38495, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], max_length=4),
        ),
    ]
