# Generated by Django 4.2.6 on 2023-10-17 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_idea_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2023, 10, 17, 5, 56, 51, 15925, tzinfo=datetime.timezone.utc)),
        ),
    ]
